stages:
  - stage: ubuntu_latest
    displayName: 'ubuntu-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: Compile
        displayName: 'âš™ï¸ Compile'
        dependsOn: [  ]
        steps:
          - task: CmdLine@2
            inputs:
              script: './build.cmd Restore Compile --skip'
      - job: Test
        displayName: 'ğŸš¦ Test ğŸ§©'
        dependsOn: [ Compile ]
        strategy:
          parallel: 2
        steps:
          - task: CmdLine@2
            inputs:
              script: './build.cmd Test --skip --test-partition $(System.JobPositionInPhase)'
          - task: PublishBuildArtifacts@1
            inputs:
              artifactName: test-results
              pathtoPublish: 'output/test-results'
      - job: Pack
        displayName: 'ğŸ“¦ Pack'
        dependsOn: [ Compile ]
        steps:
          - task: CmdLine@2
            inputs:
              script: './build.cmd Pack --skip'
          - task: PublishBuildArtifacts@1
            inputs:
              artifactName: packages
              pathtoPublish: 'output/packages'